### ISSUE TITLE
TypeError: can't multiply sequence by non-int of type 'str'

### ISSUE THREAD

**Issue by demonsec666** [Fmk0/scripts#1]
![image](https://user-images.githubusercontent.com/24873495/55693114-ce959780-59df-11e9-803a-f7a735609c1f.png)

**Comment by Fmk0** [comment]
I will check during this weekend.
Thx for the report.

**Comment by ferran7e** [comment]
Any update on this issue? :) -- Using Python 3.7.3

**Comment by Fmk0** [comment]
Resolved on 0.2
